linters:
  enable:
    - goimports
    - gofmt
    - gofumpt

linters-settings:
  goimports:
    local-prefixes: github.com/pd93
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
