version: "3"

tasks:
  examples:
    description: "Run all examples"
    cmds:
      - go run ./examples/...

  lint:
    description: "Run linter"
    cmds:
      - golangci-lint run

  test:
    description: "Run all tests"
    cmds:
      - go test ./...

  bench:
    description: "Run all benchmarks"
    cmds:
      - go test -bench=. ./...
