name: Lint

on:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  lint:
    name: Lint Go code
    strategy:
      matrix:
        go-version:
          - 1.20.x
          - 1.21.x
          - 1.22.x
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ${{matrix.go-version}}
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-version}}
      - name: Check out code
        uses: actions/checkout@v4
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.1
