name: Test

on:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version:
          - 1.20.x
          - 1.21.x
          - 1.22.x
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{matrix.platform}}
    steps:
      - name: Set up Go ${{matrix.go-version}}
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-version}}
      - name: Check out code
        uses: actions/checkout@v4
      - name: Test
        run: go test -v ./...
